import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

from glnet.models.adaptive_fusion import AdaptiveReliabilityEstimator
from glnet.models.bev_fusion import BEVDeformableFusion
from glnet.utils.params import ModelParams


def _get_parallel_beam():
    try:
        from torch_radon import ParallelBeam
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            'torch_radon is required only when running the yaw/spec branch. '
            'The BEV feature export path does not use it.'
        ) from exc
    return ParallelBeam


def ring_sharp_row_fft(input):
    median_output = torch.fft.fft2(input, dim=-1, norm='ortho')
    output = torch.sqrt(median_output.real ** 2 + median_output.imag ** 2 + 1e-15)
    return output, median_output


def ring_sharp_column_fft(input):
    median_output = torch.fft.fft2(input, dim=-2, norm='ortho')
    output = torch.sqrt(median_output.real ** 2 + median_output.imag ** 2 + 1e-15)
    output = torch.fft.fftshift(output)
    return output, median_output


def ring_sharp_fft(input):
    median_output = torch.fft.fft2(input, norm='ortho')
    output = torch.sqrt(median_output.real ** 2 + median_output.imag ** 2 + 1e-15)
    output = torch.fft.fftshift(output)
    return output, median_output


def ring_sharp_compute_spec(x, rot_ang=2 * np.pi):
    n_angles = x.shape[-2]
    image_size = x.shape[-1]
    angles = torch.from_numpy(np.linspace(0, rot_ang, n_angles).astype(np.float32)).to(x.device)
    ParallelBeam = _get_parallel_beam()
    radon = ParallelBeam(image_size, angles)
    sinogram = radon.forward(x)
    spec, _ = ring_sharp_row_fft(sinogram)
    return spec, sinogram


def run_ring_sharp_downstream(
    owner,
    bev,
    depth_pred=None,
    bev_confidence=None,
    yaw_module=None,
    trans_module=None,
    extra_outputs=None,
):
    """Shared RING# downstream path after a BEV feature map is available."""
    b, _, _, _ = bev.shape

    if owner.coordinates == 'polar':
        out_h = owner.radius
        out_w = owner.theta
        new_h = torch.linspace(0, 1, out_h, device=bev.device).view(-1, 1).repeat(1, out_w)
        new_w = torch.pi * torch.linspace(0, 2, out_w, device=bev.device).repeat(out_h, 1)
        grid_xy = torch.cat((new_h.unsqueeze(2), new_w.unsqueeze(2)), dim=2)
        new_grid = grid_xy.clone()
        new_grid[..., 0] = grid_xy[..., 0] * torch.cos(grid_xy[..., 1])
        new_grid[..., 1] = grid_xy[..., 0] * torch.sin(grid_xy[..., 1])
        new_grid = new_grid.unsqueeze(0).repeat(b, 1, 1, 1)
        polar_bev = F.grid_sample(bev, new_grid, align_corners=False)
    else:
        polar_bev = None

    if yaw_module is None:
        raise ValueError('run_ring_sharp_downstream requires a yaw_module')

    if owner.yaw_mode == 0:
        bev_yaw = yaw_module(bev)
        spec, sinogram = ring_sharp_compute_spec(bev_yaw)
    elif owner.yaw_mode == 1:
        _, sinogram = ring_sharp_compute_spec(bev)
        sinogram = yaw_module(sinogram)
        spec, _ = ring_sharp_row_fft(sinogram)
    else:
        bev_yaw = bev
        spec, sinogram = ring_sharp_compute_spec(bev_yaw)

    if owner.trans_mode == 0:
        bev_trans = None
    elif owner.trans_mode == 1:
        bev_trans = trans_module(bev) if trans_module is not None else bev
    else:
        bev_trans = bev

    if owner.descriptor_from_spec:
        x = owner.spec_descriptor_head(spec)
    else:
        x = torch.sum(spec, dim=-2).reshape(b, -1)
        if owner.use_normalize:
            x = F.normalize(x, dim=-1)

    output = {
        'bev': bev,
        'depth': depth_pred,
        'polar_bev': polar_bev,
        'bev_trans': bev_trans,
        'spec': spec,
        'global': x,
        'confidence': bev_confidence,
    }
    if extra_outputs:
        output.update(extra_outputs)
    return output


class RINGSharpVL(nn.Module):
    """RING# visual-LiDAR BEV fusion model.

    Visual BEV is generated by RINGSharpV.
    LiDAR BEV feature is generated by RINGSharpL.
    The fused BEV is then passed to the unchanged RING#/RT/FFT downstream path.
    """

    def __init__(self, model_params: ModelParams):
        super().__init__()
        if model_params.xyz_aug:
            raise ValueError(
                'RINGSharpVL requires xyz_aug=False. The current dataset pipeline applies xyz_aug only to LiDAR, '
                'which would break visual/LiDAR BEV alignment.'
            )

        from glnet.models.localizer.ring_sharp_v import RINGSharpV
        from glnet.models.localizer.ring_sharp_l import RINGSharpL

        self.visual_branch = RINGSharpV(model_params)
        self.lidar_branch = RINGSharpL(model_params)
        if self.visual_branch.feature_dim != model_params.bev_fusion_visual_channels:
            raise ValueError(
                f'Visual branch BEV channels={self.visual_branch.feature_dim}, '
                f'but bev_fusion_visual_channels={model_params.bev_fusion_visual_channels}.'
            )
        if self.lidar_branch.feature_dim != model_params.bev_fusion_lidar_channels:
            raise ValueError(
                f'LiDAR branch BEV channels={self.lidar_branch.feature_dim}, '
                f'but bev_fusion_lidar_channels={model_params.bev_fusion_lidar_channels}.'
            )

        self.yaw_mode = 1
        self.trans_mode = 0
        self.theta = model_params.theta
        self.radius = model_params.radius
        self.coordinates = model_params.coordinates
        self.use_normalize = model_params.normalize
        self.descriptor_from_spec = model_params.descriptor_from_spec
        self.global_descriptor_dim = model_params.global_descriptor_dim
        self.bev_fusion_strict_meta = model_params.bev_fusion_strict_meta
        self.bev_fusion_timestamp_tolerance_ms = model_params.bev_fusion_timestamp_tolerance_ms
        self.adaptive_fusion_enabled = model_params.adaptive_fusion
        self.feature_dim = model_params.bev_fusion_out_channels
        self.spec_descriptor_head = self.visual_branch.spec_descriptor_head if self.descriptor_from_spec else None

        self.bev_fusion = BEVDeformableFusion(
            visual_in_channels=model_params.bev_fusion_visual_channels,
            lidar_in_channels=model_params.bev_fusion_lidar_channels,
            embed_dim=model_params.bev_fusion_attn_channels,
            out_channels=model_params.bev_fusion_out_channels,
            num_heads=model_params.bev_fusion_num_heads,
            num_levels=model_params.bev_fusion_num_levels,
            num_points=model_params.bev_fusion_num_points,
            dropout=model_params.bev_fusion_dropout,
            drop_path=model_params.bev_fusion_drop_path,
            prefer_cuda_ms_deform_attn=model_params.bev_fusion_prefer_cuda_ms_deform_attn,
        )
        self.adaptive_reliability_estimator = (
            AdaptiveReliabilityEstimator(
                dataset_type=model_params.dataset_type,
                rho=model_params.adaptive_fusion_rho,
                temperature=model_params.adaptive_fusion_temperature,
                use_visual_reliability=model_params.adaptive_visual_reliability,
                use_lidar_reliability=model_params.adaptive_lidar_reliability,
                eps=model_params.adaptive_eps,
                lidar_reliability_mode=model_params.adaptive_lidar_reliability_mode,
                lidar_downsample_voxel_size=model_params.adaptive_lidar_reliability_downsample,
                lidar_knn=model_params.adaptive_lidar_reliability_k,
                lidar_min_neighbors=model_params.adaptive_lidar_reliability_min_neighbors,
            )
            if self.adaptive_fusion_enabled
            else None
        )

        self.occ_conv_yaw = nn.Sequential(
            nn.Conv2d(self.feature_dim, self.feature_dim, kernel_size=3, padding=1, stride=1),
            nn.BatchNorm2d(self.feature_dim),
            nn.ReLU(inplace=True),
            nn.Conv2d(self.feature_dim, 1, kernel_size=3, padding=1, stride=1),
            nn.BatchNorm2d(1),
            nn.Sigmoid(),
        )
        self.occ_conv_trans = nn.Sequential(
            nn.Conv2d(self.feature_dim, self.feature_dim, kernel_size=3, padding=1, stride=1),
            nn.BatchNorm2d(self.feature_dim),
            nn.ReLU(inplace=True),
            nn.Conv2d(self.feature_dim, 1, kernel_size=3, padding=1, stride=1),
            nn.BatchNorm2d(1),
            nn.Sigmoid(),
        )

    def extract_vision_bev(self, batch, return_reliability=False):
        return self.visual_branch.extract_vision_bev(batch, return_reliability=return_reliability)

    def extract_bev_features(self, batch):
        return self.extract_vision_bev(batch)

    def extract_lidar_bev(self, batch):
        return self.lidar_branch.extract_lidar_bev(batch)

    def extract_fused_bev(self, batch):
        return_visual_reliability = (
            self.adaptive_fusion_enabled
            and self.adaptive_reliability_estimator is not None
            and self.adaptive_reliability_estimator.use_visual_reliability
        )
        visual_outputs = self.extract_vision_bev(batch, return_reliability=return_visual_reliability)
        lidar_outputs = self.extract_lidar_bev(batch)
        bev_meta = batch.get('bev_meta')
        adaptive = None
        if self.adaptive_fusion_enabled:
            adaptive = self.adaptive_reliability_estimator(
                batch=batch,
                visual_bev=visual_outputs['bev'],
                lidar_bev=lidar_outputs['bev'],
                visual_outputs=visual_outputs,
                lidar_outputs=lidar_outputs,
            )

        fusion_outputs = self.bev_fusion(
            visual_outputs['bev'],
            lidar_outputs['bev'],
            adaptive=adaptive,
            visual_meta=bev_meta,
            lidar_meta=bev_meta,
            strict_meta=self.bev_fusion_strict_meta,
            timestamp_tolerance_ms=self.bev_fusion_timestamp_tolerance_ms,
            return_intermediates=False,
        )
        del bev_meta
        return visual_outputs, lidar_outputs, fusion_outputs

    def forward(self, batch):
        visual_outputs, lidar_outputs, fusion_outputs = self.extract_fused_bev(batch)
        visual_bev = visual_outputs['bev']
        lidar_bev = lidar_outputs['bev']
        fused_bev = fusion_outputs['fused_bev']
        extra_outputs = {
            'visual_bev': visual_bev,
            'lidar_bev': lidar_bev,
            'fused_bev': fused_bev,
            'bev_fusion_backend': fusion_outputs['attention_backend'],
        }
        if 'adaptive' in fusion_outputs:
            extra_outputs['adaptive'] = fusion_outputs['adaptive']

        return run_ring_sharp_downstream(
            self,
            fused_bev,
            depth_pred=visual_outputs['depth'],
            bev_confidence=visual_outputs['confidence'],
            yaw_module=self.occ_conv_yaw,
            trans_module=self.occ_conv_trans,
            extra_outputs=extra_outputs,
        )

    def print_info(self):
        print('Model class: RING#-VL')
        n_params = sum(param.nelement() for param in self.parameters())
        print('Total parameters: {}'.format(n_params))
        n_params = sum(param.nelement() for param in self.visual_branch.encoder.parameters())
        print('Visual encoder parameters: {}'.format(n_params))
        n_params = sum(param.nelement() for param in self.lidar_branch.encoder.parameters())
        print('LiDAR BEV encoder parameters: {}'.format(n_params))
